### ISSUE TITLE
include of non-modular header JSQSystemSoungPlayer error

### ISSUE THREAD

**Issue by marcioarantes-ww** [jessesquires/JSQMessagesViewController#1497]
I want to use JSQMessagesViewController as a dependency to my swift pod. When I build my example app I get the old non-modular header error related to the JSQSystemSoundPlayer but I don't know how to get around it with XCode 7.

Podspec: 
s.dependency 'JSQSystemSoundPlayer' 
s.dependency 'JSQMessagesViewController', '7.2.0'
 #Also tried 5.3.2

<img width="695" alt="screen shot 2016-03-10 at 12 16 07 pm" src="https://cloud.githubusercontent.com/assets/12056463/13683314/e01336fc-e6ba-11e5-94a0-a609fcc16d93.png">
<img width="1440" alt="screen shot 2016-03-10 at 12 09 38 pm" src="https://cloud.githubusercontent.com/assets/12056463/13683317/e0737c56-e6ba-11e5-8fc6-b1b7bb5c02dc.png">

**Comment by Mackarous** [comment]
Hi @marcioarantes-ww 

I have actually had similar experiences with this problem. The issue is that Swift doesn't play nice with importing non-modular frameworks into frameworks. Essentially, you will only run into this problem when bundling a framework inside another. There is a simple solution, however it requires some work `JSQSystemSoundPlayer` as well as `JSQMessagesViewController`. 

@jessesquires Both projects (`JSQSystemSoundPlayer` as well as `JSQMessagesViewController`) will need to have the following Xcode project setting: `DEFINES_MODULE = YES;` Should I put two PRs through?

**Comment by jessesquires** [comment]
@Mackarous :+1: :+1: :+1: :+1:

**Comment by jessesquires** [comment]
Related: #927, #1283, #1284

**Comment by marcioarantes-ww** [comment]
Thank you guys! :)

**Comment by Mackarous** [comment]
Hey sorry for the delay,

@jessesquires:

Upon further investigation, it turns out that `JSQSystemSoundPlayer` is not an issue, and can remain as is. The change that needs to be done is in the `JSQMessagesViewController` Podfile. The Podfile requires the following changes:

```
platform :ios, '8.0'
use_frameworks!
```

This will use frameworks instead of static libraries for the included projects, which in the case of `JSQMessagesViewController` is only `JSQSystemSoundPlayer`. This will allow the import of `JSQSystemSoundPlayer` as a module, and it should resolve the errors that @marcioarantes-ww is having. **I have only been able to test in a very controlled environment** as I do not know the exact intricacies of @marcioarantes-ww's project.

Summary of changes to `JSQMessagesViewController`:
- Change Podfile platform to iOS 8
- Change Podfile to use frameworks instead of static libraries
- Change project structure deployment target to iOS 8
- Run pod install

**Comment by jessesquires** [comment]
Thanks for the investigation and info @Mackarous ! Huge help! :bow: 

This was what I expected to hear. We'll have to target this change for version `8.0` of the library.

**Comment by marcioarantes-ww** [comment]
I believe this is incorrect. As stated above JSQMessagesViewController works fine with the use of use_frameworks! flag in the podfile but this is not what I'm doing. JSQMessagesViewController is a dependency of my own pod not a project. I was able to compile my example app by updating JSQSystemSoundPlayer+JSQMessages to include @import JSQSystemSoundPlayer;

**Comment by Mackarous** [comment]
Hey @marcioarantes-ww,

I should have elaborated further:

The reason this works is because you are importing `JSQMessagesViewController` as a dependency in your project. Making the change you suggested is specific to your project, and will actually break when using `JSQMessagesViewController` through a Podfile. The reason for that is because you are using frameworks in your Podfile which takes precedence, and since you are using `JSQMessagesViewController` as a dependency in a Podspec, it follows your Podfile's `use_frameworks!` tag. Finally, changing a file in your dependency is temporary since running a `pod update` or `pod install` will overwrite your changes. 

To ensure that `JSQMessagesViewController` works as a pod in a project Podfile _and_ a dependency in a Podspec, the changes I outlined above need to be implemented.

**Comment by marcioarantes-ww** [comment]
@Mackarous got it thanks for clarifying. Looking forward to your next update.

**Comment by jessesquires** [comment]
Thanks @Mackarous ! :tada: :smile:

**Comment by edwardvalentini** [comment]
+1 for this issue :)

**Comment by chrisscholly** [comment]
I have this issue and can't resolve it... :(
![capture d ecran 2016-04-08 a 14 00 38](https://cloud.githubusercontent.com/assets/26509/14383011/6b34e7f6-fd92-11e5-8511-8562391a294f.png)

**Comment by chrisscholly** [comment]
finally works with cocoapods 0.39.0. Do not use beta :p

**Comment by Nathan187** [comment]
I'm still getting this error.  how exactly did you fix it?  this is what my podfile looks like

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
workspace 'EODPOC'



target 'EODPOC' do
    
  
    pod 'Alamofire'
    pod 'Facebook-iOS-SDK', '~> 3.23.0', :inhibit_warnings => true
    pod 'MMDrawerController' , '~> 0.5.7'
    pod 'MMProgressHUD', :inhibit_warnings => true
    pod 'MagicalRecord', :inhibit_warnings => true, :inhibit_warnings => true, :git => 'https://github.com/magicalpanda/MagicalRecord.git', :branch => 'release/3.0'

    #pod 'FMDB'
    pod 'FMDB', :git => 'https://github.com/robertmryan/fmdb.git'

    pod 'RNCryptor', :inhibit_warnings => true
    pod 'SwiftyJSON'
   
 pod 'JSQMessagesViewController'
  #pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'

end

**Comment by edwardvalentini** [comment]
is your project structure also using ios 8.0 as the minimum deployment target? When i followed @Mackarous instructions the first time, i had a mismatch and got an error.. but if both the podfile and project are set to 8.0 then it worked

**Comment by Nathan187** [comment]
thanks for the rapid reply (no sarcasm).  i tried changing it to 8.0, 9.0, 9.2, etc.  I changed the deployment target and platform values to match but still get the error.  this was working previously but just no longer compiles

**Comment by jpsachse** [comment]
+1 on the "JSQSystemSoundPlayer/JSQSystemSoundplayer.h file not found" error using cocoapods 1.0.0.rc1.

**Comment by chrisballinger** [comment]
Encountered this with CocoaPods 1.0.0. You need to `@import JSQSystemSoundPlayer;`

**Comment by jpsachse** [comment]
It seems to work for me (for now) using Swift 2.2 with Xcode 7.3.1 and CocoaPods 1.0. It currently builds both in simulator and on device just using `import JSQMessagesViewController`

**Comment by jerembab** [comment]
It work for me ( using Swift 2.2 with Xcode 7.3.1 and CocoaPods 1.0 ) but only in simulator , in device Im getting the following errors:  'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/.../Frameworks/JSQMessagesViewController.framework> (loaded)' with name 'JSQMessagesViewController'
any ideas?

**Comment by jessesquires** [comment]
Fixed by #1649

**Comment by thuanngo1990** [comment]
I still got same issue (using swift 2.2 , xcode 7.3.1 and cocoaPods 1.0), it work only in simulator. In my devide (iphone 6 , ver 9.3.2).  My pods file also change to "platform :ios, '8.0'
use_frameworks! " @Mackarous  . It still happening.   This's message :  
 + 'JSQSystemSoundPlayer/JSQSystemSoundPlayer.h' file not found. 
 + Could not build Objective-C module 'JSQMessagesViewController'. 
Anything i can do?

**Comment by jessesquires** [comment]
The fix is on `develop` and will be included with `v8.0` of the library

**Comment by aaso** [comment]
i still got same issue (using swift 3.1 , xcode 8.3 and cocoaPods 1.0),
. My pods file also change to "platform :ios, '9.0'
use_frameworks! 

'JSQSystemSoundPlayer/JSQSystemSoundPlayer.h' file not found.
Could not build Objective-C module 'JSQMessagesViewController'.
Anything i can do? @jessesquires
