### ISSUE TITLE
Custom menu strange behaviour

### ISSUE THREAD

**Issue by relatedcode** [jessesquires/JSQMessagesViewController#1668]
### General information

- Library version(s): 7.3.3
- iOS version(s): 9.3
- Devices/Simulators affected: both
- Reproducible in the demo project? (Yes/No): Yes

## Bug report

> The custom menu is displayed only from the second time.
> After making a paste action the issue starts over.

http://relatedcode.com/JSQMessagesViewController.mov

**Comment by jessesquires** [comment]
Thanks @relatedcode !

**Comment by GianniCarlo** [comment]
The first part of the video happens because even though we registered the action, we never set it in the `[UIMenuController sharedMenu].menuItems` in the `viewDidLoad`. Then after it shows up, `didReceiveMenuWillShowNotification:` is called and that's why `Custom Action` shows up next time. 

For the second part, `JSQMessagesComposerTextView` is setting up as nil the `menuItems` in `canPerformAction:withSender:` and that's why it won't show next time the `Custom Action` in the cell next time, because it first consults the selectors before `didReceiveMenuWillShowNotification` is called

We should look into using `[[UIMenuController sharedMenu] update]` function so we can update from the demo the list of items of the menu even though it's been already displayed. My initial tests are promising, but when displaying the menu from the input field, it looks like the `update` makes the menu lose its initial frame and it gets displayed in the middle of the screen

**Comment by hemantkadam** [comment]
@relatedcode @jessesquires @GianniCarlo Even i'm facing strange issue related to UIMenuController.
When i first time load JSQMessageViewController and long press cell/messages it shows me my custom menuItems i.e. Copy, Delete and Forward.

I have UIBarButtonItem on navigationbar which opens UIActionSheet, if the sheet is dismissed no menuItems are shown after long press.

What will be the reason for this? Can anyone please help me, this is bugging me alot. Every time actionsheet is displayed UIMenuController seems to be disabled or removed :(

**Comment by GianniCarlo** [comment]
I haven't had time to continue on working on this :/. @hemantkadam yours might be related to `[UIMenuController sharedMenuController].menuItems = nil;` in `JSQMessagesComposerTextView`. I hope this weekend I get around on solving this

**Comment by hemantkadam** [comment]
Thanks @GianniCarlo This morning i tried replacing UIActionSheet with UIAlertController and guess what it worked... Don't know exactly what was the issue with UIActionsheet but my issue is fixed when I'm presenting UIAlertController using [self presentViewController:actionSheet animated:YES completion:nil];
Just saw your reply and decided to inform this fix here immediately so as you don't spend your weekend time for solving this issue.
Thanks again 👍

**Comment by Lucashuang0802** [comment]
@jessesquires I think I put a fix into this PR #1759. So, I guess this can be closed as well?

**Comment by Lucashuang0802** [comment]
btw, the way to fix it is to postpone super class to call `didReceiveMenuWillShowNotification`. Because when the super class calls `didReceiveMenuWillShowNotification`, the menu has popped already. And calling menuItems later does not seem to make `Custom Action` work. So, we have to tell it earlier.

**Comment by jessesquires** [comment]
@Lucashuang0802 👍 💯

**Comment by relatedcode** [comment]
Hi Guys!

I have pulled the latest version (7.3.4) today, but as far as I see the problem is still exists.

Or did I miss something here?

http://relatedcode.com/JSQMVC_20160727.mov

Thanks
